# Generated by Django 5.1.1 on 2024-10-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0002_remove_job_client_job_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='task_percentage',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
