# Generated by Django 5.1.1 on 2024-10-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_app_v2', '0004_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
